apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-selling-api
  namespace: ticket-selling
  labels:
    app: ticket-selling-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticket-selling-api
  template:
    metadata:
      labels:
        app: ticket-selling-api
    spec:
      containers:
      - name: api
        image: ticket-selling-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: name
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=:50051
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-selling-api
  namespace: ticket-selling
spec:
  selector:
    app: ticket-selling-api
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  type: LoadBalancer 