// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: seat_service.proto

package seat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Định nghĩa Seat
type Seat struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId     string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RowNumber   string                 `protobuf:"bytes,4,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	SeatNumber  string                 `protobuf:"bytes,5,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	Coordinates string                 `protobuf:"bytes,6,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	// Thay thế google.protobuf.Struct bằng map<string, string>
	Attributes  map[string]string `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Lưu ý: Chỉ cho phép giá trị là chuỗi
	IsAvailable bool              `protobuf:"varint,8,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	// Thay thế google.protobuf.Timestamp bằng int64 (ví dụ: Unix seconds)
	CreatedAt     int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // Lưu trữ thời gian dưới dạng int64 (ví dụ: Unix seconds)
	UpdatedAt     int64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Lưu trữ thời gian dưới dạng int64 (ví dụ: Unix seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_seat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seat) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Seat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seat) GetRowNumber() string {
	if x != nil {
		return x.RowNumber
	}
	return ""
}

func (x *Seat) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *Seat) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *Seat) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Seat) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Seat) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Seat) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Yêu cầu tạo seat
type CreateSeatRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RowNumber   string                 `protobuf:"bytes,3,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	SeatNumber  string                 `protobuf:"bytes,4,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	Coordinates string                 `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	// Thay thế google.protobuf.Struct bằng map<string, string>
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Chỉ cho phép giá trị là chuỗi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeatRequest) Reset() {
	*x = CreateSeatRequest{}
	mi := &file_seat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeatRequest) ProtoMessage() {}

func (x *CreateSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeatRequest.ProtoReflect.Descriptor instead.
func (*CreateSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSeatRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateSeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSeatRequest) GetRowNumber() string {
	if x != nil {
		return x.RowNumber
	}
	return ""
}

func (x *CreateSeatRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *CreateSeatRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *CreateSeatRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Phản hồi sau khi tạo
type CreateSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeatResponse) Reset() {
	*x = CreateSeatResponse{}
	mi := &file_seat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeatResponse) ProtoMessage() {}

func (x *CreateSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeatResponse.ProtoReflect.Descriptor instead.
func (*CreateSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSeatResponse) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

// Yêu cầu cập nhật seat
type UpdateSeatRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RowNumber   string                 `protobuf:"bytes,3,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	SeatNumber  string                 `protobuf:"bytes,4,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	Coordinates string                 `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	// Thay thế google.protobuf.Struct bằng map<string, string>
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Chỉ cho phép giá trị là chuỗi
	IsAvailable   bool              `protobuf:"varint,7,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatRequest) Reset() {
	*x = UpdateSeatRequest{}
	mi := &file_seat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatRequest) ProtoMessage() {}

func (x *UpdateSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSeatRequest) GetRowNumber() string {
	if x != nil {
		return x.RowNumber
	}
	return ""
}

func (x *UpdateSeatRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *UpdateSeatRequest) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *UpdateSeatRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UpdateSeatRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

// Phản hồi cập nhật seat
type UpdateSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeatResponse) Reset() {
	*x = UpdateSeatResponse{}
	mi := &file_seat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatResponse) ProtoMessage() {}

func (x *UpdateSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSeatResponse) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

// Yêu cầu xóa
type DeleteSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeatRequest) Reset() {
	*x = DeleteSeatRequest{}
	mi := &file_seat_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatRequest) ProtoMessage() {}

func (x *DeleteSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatRequest.ProtoReflect.Descriptor instead.
func (*DeleteSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeatResponse) Reset() {
	*x = DeleteSeatResponse{}
	mi := &file_seat_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeatResponse) ProtoMessage() {}

func (x *DeleteSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeatResponse.ProtoReflect.Descriptor instead.
func (*DeleteSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Lấy thông tin 1 seat
type GetSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatRequest) Reset() {
	*x = GetSeatRequest{}
	mi := &file_seat_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatRequest) ProtoMessage() {}

func (x *GetSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatRequest.ProtoReflect.Descriptor instead.
func (*GetSeatRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetSeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          *Seat                  `protobuf:"bytes,1,opt,name=seat,proto3" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatResponse) Reset() {
	*x = GetSeatResponse{}
	mi := &file_seat_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatResponse) ProtoMessage() {}

func (x *GetSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatResponse.ProtoReflect.Descriptor instead.
func (*GetSeatResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetSeatResponse) GetSeat() *Seat {
	if x != nil {
		return x.Seat
	}
	return nil
}

// Danh sách seat theo sự kiện
type ListSeatsByEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeatsByEventRequest) Reset() {
	*x = ListSeatsByEventRequest{}
	mi := &file_seat_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeatsByEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeatsByEventRequest) ProtoMessage() {}

func (x *ListSeatsByEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeatsByEventRequest.ProtoReflect.Descriptor instead.
func (*ListSeatsByEventRequest) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListSeatsByEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListSeatsByEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeatsByEventResponse) Reset() {
	*x = ListSeatsByEventResponse{}
	mi := &file_seat_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeatsByEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeatsByEventResponse) ProtoMessage() {}

func (x *ListSeatsByEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seat_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeatsByEventResponse.ProtoReflect.Descriptor instead.
func (*ListSeatsByEventResponse) Descriptor() ([]byte, []int) {
	return file_seat_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListSeatsByEventResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

var File_seat_service_proto protoreflect.FileDescriptor

const file_seat_service_proto_rawDesc = "" +
	"\n" +
	"\x12seat_service.proto\x12\x04seat\"\x83\x03\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"row_number\x18\x04 \x01(\tR\trowNumber\x12\x1f\n" +
	"\vseat_number\x18\x05 \x01(\tR\n" +
	"seatNumber\x12 \n" +
	"\vcoordinates\x18\x06 \x01(\tR\vcoordinates\x12:\n" +
	"\n" +
	"attributes\x18\a \x03(\v2\x1a.seat.Seat.AttributesEntryR\n" +
	"attributes\x12!\n" +
	"\fis_available\x18\b \x01(\bR\visAvailable\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x02\n" +
	"\x11CreateSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"row_number\x18\x03 \x01(\tR\trowNumber\x12\x1f\n" +
	"\vseat_number\x18\x04 \x01(\tR\n" +
	"seatNumber\x12 \n" +
	"\vcoordinates\x18\x05 \x01(\tR\vcoordinates\x12G\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2'.seat.CreateSeatRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x12CreateSeatResponse\x12\x1e\n" +
	"\x04seat\x18\x01 \x01(\v2\n" +
	".seat.SeatR\x04seat\"\xc4\x02\n" +
	"\x11UpdateSeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"row_number\x18\x03 \x01(\tR\trowNumber\x12\x1f\n" +
	"\vseat_number\x18\x04 \x01(\tR\n" +
	"seatNumber\x12 \n" +
	"\vcoordinates\x18\x05 \x01(\tR\vcoordinates\x12G\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2'.seat.UpdateSeatRequest.AttributesEntryR\n" +
	"attributes\x12!\n" +
	"\fis_available\x18\a \x01(\bR\visAvailable\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x12UpdateSeatResponse\x12\x1e\n" +
	"\x04seat\x18\x01 \x01(\v2\n" +
	".seat.SeatR\x04seat\"#\n" +
	"\x11DeleteSeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eGetSeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetSeatResponse\x12\x1e\n" +
	"\x04seat\x18\x01 \x01(\v2\n" +
	".seat.SeatR\x04seat\"4\n" +
	"\x17ListSeatsByEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"<\n" +
	"\x18ListSeatsByEventResponse\x12 \n" +
	"\x05seats\x18\x01 \x03(\v2\n" +
	".seat.SeatR\x05seats2\xdb\x02\n" +
	"\vSeatService\x12?\n" +
	"\n" +
	"CreateSeat\x12\x17.seat.CreateSeatRequest\x1a\x18.seat.CreateSeatResponse\x12?\n" +
	"\n" +
	"UpdateSeat\x12\x17.seat.UpdateSeatRequest\x1a\x18.seat.UpdateSeatResponse\x12?\n" +
	"\n" +
	"DeleteSeat\x12\x17.seat.DeleteSeatRequest\x1a\x18.seat.DeleteSeatResponse\x126\n" +
	"\aGetSeat\x12\x14.seat.GetSeatRequest\x1a\x15.seat.GetSeatResponse\x12Q\n" +
	"\x10ListSeatsByEvent\x12\x1d.seat.ListSeatsByEventRequest\x1a\x1e.seat.ListSeatsByEventResponseB\fZ\n" +
	"proto/seatb\x06proto3"

var (
	file_seat_service_proto_rawDescOnce sync.Once
	file_seat_service_proto_rawDescData []byte
)

func file_seat_service_proto_rawDescGZIP() []byte {
	file_seat_service_proto_rawDescOnce.Do(func() {
		file_seat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seat_service_proto_rawDesc), len(file_seat_service_proto_rawDesc)))
	})
	return file_seat_service_proto_rawDescData
}

var file_seat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_seat_service_proto_goTypes = []any{
	(*Seat)(nil),                     // 0: seat.Seat
	(*CreateSeatRequest)(nil),        // 1: seat.CreateSeatRequest
	(*CreateSeatResponse)(nil),       // 2: seat.CreateSeatResponse
	(*UpdateSeatRequest)(nil),        // 3: seat.UpdateSeatRequest
	(*UpdateSeatResponse)(nil),       // 4: seat.UpdateSeatResponse
	(*DeleteSeatRequest)(nil),        // 5: seat.DeleteSeatRequest
	(*DeleteSeatResponse)(nil),       // 6: seat.DeleteSeatResponse
	(*GetSeatRequest)(nil),           // 7: seat.GetSeatRequest
	(*GetSeatResponse)(nil),          // 8: seat.GetSeatResponse
	(*ListSeatsByEventRequest)(nil),  // 9: seat.ListSeatsByEventRequest
	(*ListSeatsByEventResponse)(nil), // 10: seat.ListSeatsByEventResponse
	nil,                              // 11: seat.Seat.AttributesEntry
	nil,                              // 12: seat.CreateSeatRequest.AttributesEntry
	nil,                              // 13: seat.UpdateSeatRequest.AttributesEntry
}
var file_seat_service_proto_depIdxs = []int32{
	11, // 0: seat.Seat.attributes:type_name -> seat.Seat.AttributesEntry
	12, // 1: seat.CreateSeatRequest.attributes:type_name -> seat.CreateSeatRequest.AttributesEntry
	0,  // 2: seat.CreateSeatResponse.seat:type_name -> seat.Seat
	13, // 3: seat.UpdateSeatRequest.attributes:type_name -> seat.UpdateSeatRequest.AttributesEntry
	0,  // 4: seat.UpdateSeatResponse.seat:type_name -> seat.Seat
	0,  // 5: seat.GetSeatResponse.seat:type_name -> seat.Seat
	0,  // 6: seat.ListSeatsByEventResponse.seats:type_name -> seat.Seat
	1,  // 7: seat.SeatService.CreateSeat:input_type -> seat.CreateSeatRequest
	3,  // 8: seat.SeatService.UpdateSeat:input_type -> seat.UpdateSeatRequest
	5,  // 9: seat.SeatService.DeleteSeat:input_type -> seat.DeleteSeatRequest
	7,  // 10: seat.SeatService.GetSeat:input_type -> seat.GetSeatRequest
	9,  // 11: seat.SeatService.ListSeatsByEvent:input_type -> seat.ListSeatsByEventRequest
	2,  // 12: seat.SeatService.CreateSeat:output_type -> seat.CreateSeatResponse
	4,  // 13: seat.SeatService.UpdateSeat:output_type -> seat.UpdateSeatResponse
	6,  // 14: seat.SeatService.DeleteSeat:output_type -> seat.DeleteSeatResponse
	8,  // 15: seat.SeatService.GetSeat:output_type -> seat.GetSeatResponse
	10, // 16: seat.SeatService.ListSeatsByEvent:output_type -> seat.ListSeatsByEventResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_seat_service_proto_init() }
func file_seat_service_proto_init() {
	if File_seat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seat_service_proto_rawDesc), len(file_seat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seat_service_proto_goTypes,
		DependencyIndexes: file_seat_service_proto_depIdxs,
		MessageInfos:      file_seat_service_proto_msgTypes,
	}.Build()
	File_seat_service_proto = out.File
	file_seat_service_proto_goTypes = nil
	file_seat_service_proto_depIdxs = nil
}
